# This is a basic workflow to help you get started with Actions
name: "Trying to get"
description: "An action that does awesome things."
inputs:
  parameter-name:
    description: 'An input parameter'

outputs:
  output-value-name:
    description: 'A value returned by the action'
runs: 'docker'
image: 'email'

branding :
  icon : 'power'
  color : 'yellow'
  
