|-- my-repo (test-)
|   |** .github
|       |** main.workflow

workflow "test" {
  on = "EVENT"
  resolves = "ACTION3"
}

action "ACTION1" {
  uses = "docker://path"
}

action "ACTION2" {
  needs = "ACTION1"
  uses = "docker://visual_studio"
}

action "ACTION3" {
  needs = "ACTION2"
  uses = "docker://mail-Id"
}
